const recentDocuments = [
  { title: 'Promises', updatedDate: '07-06-2024', url: '/src/pages/languages/javascript/advanced-topics/asynchronous-programming/promises.html' },
  { title: 'Running Tests', updatedDate: '06-22-2024', url: '/src/pages/languages/javascript/advanced-topics/testing/running-test.html' },
  { title: 'Methodologies', updatedDate: '06-21-2024', url: '/src/pages/languages/javascript/advanced-topics/testing/methodologies.html' },
  { title: 'Frameworks', updatedDate: '06-20-2024', url: '/src/pages/languages/javascript/advanced-topics/testing/frameworks.html' },
  { title: 'Testing', updatedDate: '06-20-2024', url: '/src/pages/languages/javascript/advanced-topics/testing.html' },
  { title: 'Modules', updatedDate: '06-18-2024', url: '/src/pages/languages/javascript/advanced-topics/modules.html' },
  { title: 'Classes', updatedDate: '', url: '/src/pages/languages/javascript/fundamentals/object-oriented-programming/classes.html' },
  { title: 'Git Init', updatedDate: '', url: 'src/pages/systems/git/commands/git-init.html' },
  { title: 'Git', updatedDate: '', url: '/src/pages/systems/git.html' },
  { title: 'querySelectorAll()', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document/instance-methods/querySelectorAll.html' },
  { title: 'querySelector()', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document/instance-methods/querySelector.html' },
  {
    title: 'getElementsByClassName()',
    updatedDate: '',
    url: '/src/pages/languages/javascript/interfaces/dom/document/instance-methods/getElementsByClassName.html',
  },
  { title: 'getElementById()', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document/instance-methods/getElementById.html' },
  { title: 'createElement()', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document/instance-methods/createElement.html' },
  { title: 'Events', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document/events.html' },
  { title: 'Instance Properties', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document/instance-properties.html' },
  { title: 'Instance Methods', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document/instance-methods.html' },
  { title: 'Element', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/element.html' },
  { title: 'Document', updatedDate: '', url: '/src/pages/languages/javascript/interfaces/dom/document.html' },
  { title: 'JavaScript', updatedDate: '', url: '/src/pages/languages/javascript.html' },
];
